name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.1.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.9
      - databricks_cli==0.8.7
