name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pytest
  - pip=24.3.1
  - requests=2.32.5
  - scikit-learn=1.7.2
  - pandas=2.3.2
  - numpy=2.1.0
  - pip:
      - mlflow==3.3.2
      - wandb==0.24.0
      - -e ..
