wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    session_history: code/_session_history.ipynb
    start_time: 1706761856.058285
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 1
      - 5
