wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1706899957.061938
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.9
      8:
      - 5
max_tfidf_features:
  desc: null
  value: 5
output_artifact:
  desc: null
  value: random_forest_export.csv
random_seed:
  desc: null
  value: 42
rf_config:
  desc: null
  value: rf_config
stratify_by:
  desc: null
  value: neighbourhood_group
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
