name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - requests=2.24.0
  - pyarrow=10.0.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
