name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pytest
  - pip=24.3.1
  - requests=2.32.5
  - pyarrow=21.0.0
  - pip:
      - mlflow==3.3.2
      - wandb==0.24.0
      - -e ..
