name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pip=24.3.1
  - requests=2.32.5
  - pyarrow=21.0.0
  - pip:
      - mlflow==3.4.0
      - wandb==0.22.0
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
